# Generated by Django 5.2.8 on 2025-12-11 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('branch', models.CharField(blank=True, max_length=150)),
                ('routing_no', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('level', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('rate_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PFSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('employee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('employer_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.grade')),
            ],
        ),
        migrations.CreateModel(
            name='SalarySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('house_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medical', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport', models.DecimalField(decimal_places=2, max_digits=12)),
                ('others', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='settings_app.grade')),
            ],
        ),
    ]
