# Generated by Django 5.2.8 on 2026-01-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_employeecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTEligibilitySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.designation')),
                ('employee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.employeecategory')),
            ],
            options={
                'unique_together': {('employee_category', 'designation')},
            },
        ),
        migrations.DeleteModel(
            name='OTSetting',
        ),
    ]
