# Generated by Django 5.2.8 on 2026-01-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0003_oteligibilitysetting_delete_otsetting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designation",
            name="grade",
        ),
        migrations.AddField(
            model_name="designation",
            name="employee_category",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings_app.employeecategory",
            ),
        ),
    ]
