# Generated by Django 5.2.8 on 2026-01-26 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_remove_designation_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oteligibilitysetting',
            name='ot_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='oteligibilitysetting',
            name='working_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oteligibilitysetting',
            name='working_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='employee_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='settings_app.employeecategory'),
            preserve_default=False,
        ),
    ]
