# Generated by Django 5.2.8 on 2026-01-27 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_oteligibilitysetting_ot_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave_days', models.PositiveIntegerField(default=0)),
                ('sick_leave_days', models.PositiveIntegerField(default=0)),
                ('earned_leave_days', models.PositiveIntegerField(default=0)),
                ('maternity_leave_days', models.PositiveIntegerField(default=0)),
                ('paternity_leave_days', models.PositiveIntegerField(default=0)),
                ('funeral_leave_days', models.PositiveIntegerField(default=0)),
                ('compensatory_leave_days', models.PositiveIntegerField(default=0)),
                ('unpaid_leave_days', models.PositiveIntegerField(default=0)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.designation')),
                ('employee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.employeecategory')),
            ],
            options={
                'unique_together': {('employee_category', 'designation')},
            },
        ),
    ]
