# Generated by Django 5.2.8 on 2026-01-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_leavesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesettings',
            name='carry_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavesettings',
            name='next_year_adjustment',
            field=models.BooleanField(default=False),
        ),
    ]
