# Generated by Django 5.2.8 on 2026-01-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_leavesettings_carry_forward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesettings',
            name='sandwitch_leave',
            field=models.BooleanField(default=False),
        ),
    ]
