# Generated by Django 5.2.8 on 2026-01-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_leavesettings_sandwitch_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesettings',
            name='leave_year',
            field=models.CharField(default='Calendar Year', max_length=20),
        ),
    ]
