# Generated by Django 5.2.8 on 2026-01-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0009_leavesettings_leave_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavesettings',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='leavesettings',
            name='leave_year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterUniqueTogether(
            name='leavesettings',
            unique_together={('leave_year', 'employee_category', 'designation')},
        ),
    ]
