# Generated by Django 5.2.8 on 2026-01-29 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_add_employee_type_to_leavesettings'),
        ('settings_app', '0010_alter_leavesettings_unique_together_and_more'),
    ]

    operations = [
    ]
