# Generated by Django 5.2.8 on 2026-01-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapplication",
            name="rejoin_after_leave",
            field=models.DateField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
