# Generated by Django 5.2.8 on 2026-01-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaveapplication_rejoin_after_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='application_for',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
