# Generated by Django 5.2.8 on 2026-01-24 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('settings_app', '0002_employeecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic', models.JSONField(default=dict)),
                ('house_rent', models.JSONField(default=dict)),
                ('medical', models.JSONField(default=dict)),
                ('food', models.JSONField(default=dict)),
                ('transport', models.JSONField(default=dict)),
                ('others1', models.JSONField(default=dict)),
                ('others2', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.employeecategory')),
            ],
            options={
                'unique_together': {('employee_type',)},
            },
        ),
    ]
