# Generated by Django 5.2.8 on 2026-01-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_salarypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypolicy',
            name='conveyance_allowance',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='salarypolicy',
            name='mobile_allowance',
            field=models.JSONField(default=dict),
        ),
    ]
