# Generated by Django 5.2.8 on 2025-12-11 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('join_date', models.DateField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('f_bangla_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('m_bangla_name', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('nid_no', models.CharField(blank=True, max_length=100)),
                ('birth_certificate', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('spouse_name_bangla', models.CharField(blank=True, max_length=100)),
                ('spouse_mobile', models.CharField(blank=True, max_length=30)),
                ('nominee_name', models.CharField(blank=True, max_length=100)),
                ('nominee_name_bangla', models.CharField(blank=True, max_length=100)),
                ('nominee_relation', models.CharField(blank=True, max_length=50)),
                ('nominee_mobile', models.CharField(blank=True, max_length=30)),
                ('nominee_nid', models.CharField(blank=True, max_length=100)),
                ('nominee_country', models.CharField(blank=True, max_length=50)),
                ('nominee_division', models.CharField(blank=True, max_length=50)),
                ('nominee_district', models.CharField(blank=True, max_length=50)),
                ('nominee_upazila', models.CharField(blank=True, max_length=50)),
                ('nominee_post_code', models.CharField(blank=True, max_length=20)),
                ('nominee_village', models.TextField(blank=True)),
                ('nominee_village_bangla', models.TextField(blank=True)),
                ('emg_contact_name', models.CharField(blank=True, max_length=100)),
                ('emg_contact_phone', models.CharField(blank=True, max_length=30)),
                ('emg_contact_relation', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('division', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('upazila', models.CharField(blank=True, max_length=50)),
                ('post_code', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('village', models.TextField(blank=True)),
                ('village_bangla', models.TextField(blank=True)),
                ('local_auth_name', models.CharField(blank=True, max_length=100)),
                ('local_auth_mobile', models.CharField(blank=True, max_length=30)),
                ('local_auth_relation', models.CharField(blank=True, max_length=50)),
                ('identity_mark', models.TextField(blank=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('employee_type', models.CharField(choices=[('PER', 'Permanent'), ('CON', 'Contract'), ('INT', 'Intern'), ('PT', 'Part Time')], default='PER', max_length=3)),
                ('employment_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CS', 'Casual')], default='FT', max_length=2)),
                ('documents', models.FileField(blank=True, null=True, upload_to='employee_docs/')),
                ('confirm_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=100)),
                ('pf_member', models.BooleanField(default=False)),
                ('pf_no', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.bank')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.designation')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.group')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
