# Generated by Django 5.2.8 on 2026-01-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_food_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='food_allowance',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
