# Generated by Django 5.2.8 on 2025-12-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nominee_union',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
