# Generated by Django 5.2.8 on 2025-12-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_nominee_union'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nominee_village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nominee_village_bangla',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
