# Generated by Django 5.2.8 on 2025-12-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_employee_designation_employee_ot_eligibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
