# Generated by Django 5.2.8 on 2025-12-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='group',
            new_name='group_name',
        ),
    ]
