# Generated by Django 5.2.8 on 2025-12-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_leave_effective_employee_attendance_bonus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='documents',
            new_name='education_certificate_docs',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_account_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pf_member',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pf_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='probation_end_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='education_certificate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_birthcertificate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_birthcertificate_docs',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_id_docs',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_exp_certificate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_exp_certificate_docs',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nominee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nominee_id_docs',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='training_certificate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='training_certificate_docs',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
    ]
