# Generated by Django 5.2.8 on 2025-12-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_rename_documents_employee_education_certificate_docs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='others_docs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='others_docs_file',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
    ]
