# Generated by Django 5.2.8 on 2026-01-08 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_designation_employee_grade'),
        ('settings_app', '0002_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.unit'),
        ),
    ]
