# Generated by Django 5.2.8 on 2026-01-08 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_unit'),
        ('settings_app', '0003_floor_division_department_line_section_subsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.floor'),
        ),
        migrations.AddField(
            model_name='employee',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.line'),
        ),
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.section'),
        ),
        migrations.AddField(
            model_name='employee',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.subsection'),
        ),
    ]
