# Generated by Django 5.2.8 on 2026-01-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_department_employee_floor_employee_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='educations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_experiences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='trainings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeOtherDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='employee_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_documents', to='employees.employee')),
            ],
        ),
    ]
