# Generated by Django 5.2.8 on 2026-01-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employee_educations_employee_job_experiences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_image_docs',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
    ]
