# Generated by Django 5.2.8 on 2026-01-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_employee_emp_image_employee_emp_image_docs'),
        ('settings_app', '0003_floor_division_department_line_section_subsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='division_add',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.division'),
        ),
    ]
