# Generated by Django 5.2.8 on 2026-01-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_employee_division_add_alter_employee_division'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='division_add',
            new_name='address_division',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='nominee_division',
            new_name='nominee_address_division',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='degree_title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='education_board',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='institute_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='institute_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_company_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_end_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_start_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='leave_reason',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='major_subject',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='others_docs',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='others_docs_file',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='passing_year',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='result',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='training_duration',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='training_institute',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='training_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='training_result',
        ),
        migrations.AlterField(
            model_name='employee',
            name='attendance_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='conveyance_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='educations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gross_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='house_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='insurance_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_experiences',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='medical_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='stamp_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='trainings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='transport_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
